name: Deploy ESX Core to FiveM Server

on:
  push:
    branches:
      - custom-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # Check if there's a newer version, using hypothetical v0.5.4 here

    - name: Sync ESX Core contents to server
      run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" . michaelcollins@109.228.52.77:/home/michaelcollins/gaming-servers/MOJRP2/
